version: "3.7"

services:
  postgres:
    container_name: "postgres-db-cp"
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=zhenya_z
      - POSTGRES_DB=cp
    ports:
      - "5432:5432"